variables:
  VERSION : "0.1.3-SNAPSHOT"


image: maven:3.6.3-openjdk-17-slim

stages:
  - sonarcloud-integration
  - build
  - image-push
  - test
  - image-push
  - deploy

  
mvn-build-auth:
  stage:  build
  script: 
    - cd auth_service 
    -  mvn clean package -DskipTests
  artifacts:
    paths:
      - auth_service /target
    expire_in: 2 hours



container-image-auth:
  stage: image-push
  dependencies:
    - mvn-build-auth
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --build-arg MYSQL_USER=${MYSQL_USER}
      --build-arg MYSQL_PASSWORD=${MYSQL_PASSWORD}
      --build-arg MYSQL_URL=${MYSQL_URL}
      --build-arg CLIENT_SECRET=${CLIENT_SECRET}
      --build-arg CLIENT_ID=${CLIENT_ID}
      --build-arg AUTH_DOMAIN=${AUTH_DOMAIN}
      --build-arg API_TOKEN=${API_TOKEN}
      --context "${CI_PROJECT_DIR}/auth_service"
      --dockerfile "${CI_PROJECT_DIR}/auth_service /src/main/docker/Dockerfile.jvm"
      --destination "registry.gitlab.unige.ch/pinfo-2023/pinfo-2/project-ecommerce/auth:${VERSION}"



 
deploy:
  stage: deploy
  image: alpine/helm:3.2.1
  script:
    - export KUBECONFIG=${KUBECONFIG}
    - helm uninstall invia --namespace default
    - helm upgrade --install invia ./helm-chart --namespace default








