variables:
  VERSION : "0.1.3-SNAPSHOT"


image: maven:3.6.3-openjdk-17-slim

stages:
  - sonarcloud-integration
  - build
  - image-push
  - test
  - image-push
  - deploy

sonarcloud-check-branch:
  stage: sonarcloud-integration
  image: maven:3.6.3-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - mvn verify sonar:sonar -Dsonar.projectKey=invia -Dsonar.organization=$ORG -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

mvn-build-stock-management:
  stage:  build
  script: 
    - cd stock-management
    -  mvn clean package -DskipTests
  artifacts:
    paths:
      - stock-management/target
    expire_in: 2 hours
  only:
    - main
    - schedules
    - denis


test-stock-management:
  stage: test
  dependencies:
    - mvn-build-stock-management
  script:
    - cd stock-management
    - mvn help:evaluate -Dexpression=project.version -q -DforceStdout
    - mvn test
  only:
    - main
    - denis


container-image-stock-management:
  stage: image-push
  dependencies:
    - mvn-build-stock-management
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --build-arg MYSQL_USER=${MYSQL_USER}
      --build-arg MYSQL_PASSWORD=${MYSQL_PASSWORD}
      --build-arg MYSQL_URL=${MYSQL_URL}
      --context "${CI_PROJECT_DIR}/stock-management"
      --dockerfile "${CI_PROJECT_DIR}/stock-management/src/main/docker/Dockerfile.jvm"
      --destination "registry.gitlab.unige.ch/pinfo-2023/pinfo-2/project-ecommerce/stock-management:${VERSION}"
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\[production\].*/
      - $CI_PIPELINE_SOURCE == "schedule"


mvn-build-customization:
  stage:  build
  script: 
    - cd customization 
    -  mvn clean package -DskipTests
  artifacts:
    paths:
      - customization/target
    expire_in: 2 hours
  only:
    - main
    - schedules


test-customization:
  stage: test
  dependencies:
    - mvn-build-customization 
  script:
    - cd customization 
    - mvn help:evaluate -Dexpression=project.version -q -DforceStdout
    - mvn test
  only:
    - main
    - kerfalla


container-image-backoffice-service:
  stage: image-push
  dependencies:
    - mvn-build-backoffice-service
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --build-arg MYSQL_USER=${MYSQL_USER}
      --build-arg MYSQL_PASSWORD=${MYSQL_PASSWORD}
      --build-arg MYSQL_URL=${MYSQL_URL}
      --context "${CI_PROJECT_DIR}/backoffice_service/stats"
      --dockerfile "${CI_PROJECT_DIR}/backoffice_service/stats/src/main/docker/Dockerfile.jvm"
      --destination "registry.gitlab.unige.ch/pinfo-2023/pinfo-2/project-ecommerce/back-office:latest"
  only:
    - prod


mvn-build-stats-jwt:
  stage:  build
  script: 
    - cd stats-jwt
    -  mvn clean package -DskipTests
  artifacts:
    paths:
      - stats-jwt/target
    expire_in: 2 hours
  only:
    - main
    - prod
    - kerfalla

container-image-customization:
  stage: image-push
  dependencies:
    - mvn-build-customization 
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --build-arg MYSQL_USER=${MYSQL_USER}
      --build-arg MYSQL_PASSWORD=${MYSQL_PASSWORD}
      --build-arg MYSQL_URL=${MYSQL_URL}
      --context "${CI_PROJECT_DIR}/customization"
      --dockerfile "${CI_PROJECT_DIR}/customization/src/main/docker/Dockerfile.jvm"
      --destination "registry.gitlab.unige.ch/pinfo-2023/pinfo-2/project-ecommerce/customization:${VERSION}"
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\[production\].*/
      - $CI_PIPELINE_SOURCE == "schedule"


mvn-build-payment :
  stage:  build
  script: 
    - cd payment-service 
    -  mvn clean package -DskipTests
  artifacts:
    paths:
      - payment-service/target
    expire_in: 2 hours
  only:
    - main
    - schedules


test-payment:
  stage: test
  dependencies:
    - mvn-build-payment
  script:
    - cd payment-service 
    - mvn help:evaluate -Dexpression=project.version -q -DforceStdout
    - mvn test
  only:
    - main



container-image-payment:
  stage: image-push
  dependencies:
    - mvn-build-payment
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --build-arg MYSQL_USER=${MYSQL_USER}
      --build-arg MYSQL_PASSWORD=${MYSQL_PASSWORD}
      --build-arg MYSQL_URL=${MYSQL_URL}
      --context "${CI_PROJECT_DIR}/payment-service"
      --dockerfile "${CI_PROJECT_DIR}/payment-service/src/main/docker/Dockerfile.jvm"
      --destination "registry.gitlab.unige.ch/pinfo-2023/pinfo-2/project-ecommerce/payment-service:${VERSION}"
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\[production\].*/
      - $CI_PIPELINE_SOURCE == "schedule"

  
mvn-build-backoffice-service:
  stage:  build
  script: 
    - cd backoffice_service
    -  mvn clean package -DskipTests
  artifacts:
    paths:
      - backoffice_service/target
    expire_in: 2 hours
  only:
    - main
    - schedules


test-backoffice-service:
  stage: test
  dependencies:
    - mvn-build-backoffice-service
  script:
    - cd backoffice_service
    - mvn test
  only:
    - main


container-image-backoffice-service:
  stage: image-push
  dependencies:
    - mvn-build-backoffice-service
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --build-arg MYSQL_USER=${MYSQL_USER}
      --build-arg MYSQL_PASSWORD=${MYSQL_PASSWORD}
      --build-arg MYSQL_URL=${MYSQL_URL}
      --context "${CI_PROJECT_DIR}/backoffice_service"
      --dockerfile "${CI_PROJECT_DIR}/backoffice_service/src/main/docker/Dockerfile.jvm"
      --destination "registry.gitlab.unige.ch/pinfo-2023/pinfo-2/project-ecommerce/back-office:${VERSION}"
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\[production\].*/
      - $CI_PIPELINE_SOURCE == "schedule"




mvn-build-stats-jwt:
  stage:  build
  script: 
    - cd stats-jwt
    -  mvn clean package -DskipTests
  artifacts:
    paths:
      - stats-jwt/target
    expire_in: 2 hours
  only:
    - main
    - schedules


test-stats-jwt:
  stage: test
  dependencies:
    - mvn-build-stats-jwt
  script:
    - cd stats-jwt
    - mvn test
  only:
    - main



container-image-stats-jwt:
  stage: image-push
  dependencies:
    - mvn-build-stats-jwt
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --build-arg MYSQL_USER=${MYSQL_USER}
      --build-arg MYSQL_PASSWORD=${MYSQL_PASSWORD}
      --build-arg MYSQL_URL=${MYSQL_URL}
      --context "${CI_PROJECT_DIR}/stats-jwt"
      --dockerfile "${CI_PROJECT_DIR}/stats-jwt/src/main/docker/Dockerfile.jvm"
      --destination "registry.gitlab.unige.ch/pinfo-2023/pinfo-2/project-ecommerce/stats-jwt:${VERSION}"
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\[production\].*/
      - $CI_PIPELINE_SOURCE == "schedule"

npm-build-ui:
  stage: build
  image: node:16.14.2-alpine3.14
  script:
    - cd web_ui
    - npm i
    - npm run build --prod
  only:
    - main
    - schedules


test-ui:
  stage: test
  image: node:16.14.2-alpine3.14
  script:
    - cd web_ui
    - npm i
    - npm test
  only:
    - none



container-image-web-ui:
  stage: image-push
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/web_ui"
      --dockerfile "${CI_PROJECT_DIR}/web_ui/Dockerfile"
      --destination "registry.gitlab.unige.ch/pinfo-2023/pinfo-2/project-ecommerce/web-ui:${VERSION}"
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\[production\].*/
      - $CI_PIPELINE_SOURCE == "schedule"
 
deploy:
  stage: deploy
  image: alpine/helm:3.2.1
  script:
    - export KUBECONFIG=${KUBECONFIG}
    - helm uninstall invia --namespace default
    - helm upgrade --install invia ./helm-chart --namespace default
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\[production\].*/
      - $CI_PIPELINE_SOURCE == "schedule"






