variables:
  VERSION : "0.1.3-SNAPSHOT"


image: maven:3.6.3-openjdk-17-slim

stages:
  - sonarcloud-integration
  - build
  - image-push
  - test
  - image-push
  - deploy



mvn-build-statistics:
  stage:  build
  script: 
    - cd statistic_service
    -  mvn clean package -DskipTests
  artifacts:
    paths:
      - statistic_service/target
    expire_in: 2 hours
  only:
    main


container-image-statistics:
  stage: image-push
  dependencies:
    - mvn-build-statistics 
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --build-arg MYSQL_USER=${MYSQL_USER}
      --build-arg MYSQL_PASSWORD=${MYSQL_PASSWORD}
      --build-arg MYSQL_URL=${MYSQL_URL}
      --build-arg INVIA_EMAIL=${INVIA_EMAIL}
      --build-arg GMAIL_API_SECRET=${GMAIL_API_SECRET}
      --context "${CI_PROJECT_DIR}/statistic_service"
      --dockerfile "${CI_PROJECT_DIR}/statistic_service/src/main/docker/Dockerfile.jvm"
      --destination "registry.gitlab.unige.ch/pinfo-2023/pinfo-2/project-ecommerce/statistics:${VERSION}"
  only:
    main


deploy:
  stage: deploy
  image: alpine/helm:3.2.1
  script:
    - export KUBECONFIG=${KUBECONFIG}
    - helm uninstall invia --namespace default
    - helm upgrade --install invia ./helm-chart --namespace default







