variables:
  VERSION : "0.1.3-SNAPSHOT"


image: maven:3.6.3-openjdk-17-slim

stages:
  - sonarcloud-integration
  - build
  - image-push
  - test
  - image-push
  - deploy






deploy:
  stage: deploy
  image: alpine/helm:3.2.1
  script:
    - export KUBECONFIG=${KUBECONFIG}
    - helm uninstall invia --namespace default
    - helm upgrade --install invia ./helm-chart --namespace default







