variables:
  VERSION : "0.1.6-SNAPSHOT"


image: maven:3.6.3-openjdk-17-slim

stages:
  - sonarcloud-integration
  - build
  - image-push
  - test
  - image-push
  - deploy

sonarcloud-check-branch:
  stage: sonarcloud-integration
  image: maven:3.6.3-openjdk-17-slim
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - mvn verify sonar:sonar -Dsonar.projectKey=invia -Dsonar.organization=$ORG -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN




mvn-build-customization:
  stage:  build
  script: 
    - cd customization 
    -  mvn clean package -DskipTests
  artifacts:
    paths:
      - customization/target
    expire_in: 2 hours
  only:
    - main
    - schedules


test-customization:
  stage: test
  dependencies:
    - mvn-build-customization 
  script:
    - cd customization 
    - mvn help:evaluate -Dexpression=project.version -q -DforceStdout
    - mvn test
  only:
    - schedules


container-image-customization:
  stage: image-push
  dependencies:
    - mvn-build-customization 
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --build-arg MYSQL_USER=${MYSQL_USER}
      --build-arg MYSQL_PASSWORD=${MYSQL_PASSWORD}
      --build-arg MYSQL_URL=${MYSQL_URL}
      --context "${CI_PROJECT_DIR}/customization"
      --dockerfile "${CI_PROJECT_DIR}/customization/src/main/docker/Dockerfile.jvm"
      --destination "registry.gitlab.unige.ch/pinfo-2023/pinfo-2/project-ecommerce/customization:${VERSION}"
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\[production\].*/
      - $CI_PIPELINE_SOURCE == "schedule"
      - $CI_COMMIT_REF_NAME == "main"



 
deploy:
  stage: deploy
  image: alpine/helm:3.2.1
  script:
    - export KUBECONFIG=${KUBECONFIG}
    - helm uninstall invia --namespace default
    - helm upgrade --install invia ./helm-chart --namespace default
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\[production\].*/
      - $CI_PIPELINE_SOURCE == "schedule"
      - $CI_COMMIT_MESSAGE =~ /.*\[helm\].*/
      - $CI_COMMIT_REF_NAME == "prod"







