
image: maven:3.8.3-jdk-11

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd auth-service
    - mvn clean package -DskipTests

test:
  stage: test
  script:
    - cd auth-service
    - mvn test
