apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVQnZQbk1NdHM4cGZDTjNneDA3dm96NGlUOEJJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXpNRE15TkRFeU5USXpNVm9YRFRNegpNRE15TVRFeU5USXpNVm93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2aStZcjNVT2pKaVpvMTArUGtKZDY4ZnBzR3phVkhWR3RLcWMKbjNIQTdpaDVjZ1VNNDJtMGxyNHAzWDZlamJaU1kxL3ZlREpKcWY3S3RjdUQ1bmhsWFJzSmlhWWdlcTNqbkFCOApNRzBzNDdMbTFIbnhNbTNBbHFaQ0FxanM2aW1sQ1hsOWM4VUJpQWhlK3FSVDR6MW9OVno0OVZHOXVzc1N2UmNiCldZMS8xOTBPdXVuT3dBcFNKTHZtUk93dFBjOWZpR2R3UnRLeE5FbTJFQjR4K1YvUi8rVUNpRVRiZnNJYjZMcmQKWVhWZ2g2Qkk0QTNUcmZLZCtzT1lhZ1F4QnpiK3lWclVwUTJxTW9zM0syQWxObGQ2UEhtZ21WZFFkamtpZEo0WQpTSEdJZ2gvYS9TYXRBVUZtLzFBMlFFSVhkdGZaRHZ2dGpZakZBM1FFem1zalNhTjhsd0lEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVVBWdDR0cUhFY205aHNGYUUxaFpDRkg0eExyY3dId1lEVlIwakJCZ3dGb0FVUFZ0NHRxSEUKY205aHNGYUUxaFpDRkg0eExyY3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBRlZ3OWVjblJVWGJkclB1YlBhSnUrRVVBb3NtWjQ0MzFyK1IrOHRUTmZaV0hBTi9SS0kyWUk5ZW1mVzVLCkQzNjRHSFVTSCtJeEJaZXNqanJCQmQrem02UGJaQnc5MTl3eld1R3Z6V2M4T29YMEtkM0gzRi9DbmhIZ3JFaEYKajFDQ1BMQU1zS0JzNjJPUk5LNlArZXdDdWRPa0lOYmozNjllUXNPekpFamo5Vy83WE9pclM3Wk9hK2F0Q0ZyLwpGZ0ZjbDdsVEd0QlRvNGFJSVJMQkJvM3d6SmY4OXhyZ3hhNVFrZUJnYzJOem02WXNEQkE3b1ovak1Lc3g4WkhlClZLVUZKV29OcEVzd1U1SURibVZZSFhDeGdrellpajYyclg5TkJoV3grUDRObWExeTA0R1V0Z0ZSaHRNMWNkWU0KNzNJS3hLaFE0TnphWHQ4dWFuaFR5ZFRPQ2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://129.194.10.128:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: a0dHYmxDcHIrMDRaU1NyYThlK0JWWkYyYWNMTzBuLzl0b3J6N1FLS0s4az0K
