---
openapi: 3.0.3
info:
  title: Back office api
  description: "This API allows administrators to access statistics such as the number\
    \ of users who have created an account, the number of users who have placed an\
    \ order, etc."
  license:
    name: MIT
    url: http://localhost:8081
  version: 1.0.0
tags:
- name: backoffice
  description: statistics
paths:
  /stats/abandoned_orders:
    get:
      tags:
      - Back Office Ressource
      summary: abandoned orders
      description: get the number of abandoned orders
      operationId: getNumberOfAbandonedOrders
      responses:
        "200":
          description: Operation completed
          content:
            application/json: {}
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - admin
  /stats/colors_stats:
    get:
      tags:
      - Back Office Ressource
      summary: colors stats
      description: retrieve color statistics
      operationId: getColorsStats
      responses:
        "200":
          description: Operation completed
          content:
            application/json: {}
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - admin
  /stats/connected:
    get:
      tags:
      - Back Office Ressource
      summary: Get number of users connected
      description: get the number of users who have clicked on the website
      operationId: getNumberOfUserConnected
      responses:
        "200":
          description: Operation completed
          content:
            application/json: {}
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - admin
  /stats/user_account:
    get:
      tags:
      - Back Office Ressource
      summary: retrieves the accounts created
      description: get the number of users who have created an account
      operationId: getNumbOfAccountsCreated
      responses:
        "200":
          description: Operation completed
          content:
            application/json: {}
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - admin
  /stats/user_commands:
    get:
      tags:
      - Back Office Ressource
      summary: orders placed
      description: get the number of users who have placed orders
      operationId: getNumberOfUserWhoMadeAnOrder
      responses:
        "200":
          description: Operation completed
          content:
            application/json: {}
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - admin
components:
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: bearer
      bearerFormat: JWT
