apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.auth.name }}-deployment
  namespace: {{ .Values.auth.namespace}}
spec:
  replicas: {{ .Values.auth.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.auth.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.auth.name }}
    spec:
      containers:
        - name: {{ .Values.auth.name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.group }}/{{ .Values.auth.imagename }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          ports:
            - containerPort: {{ .Values.auth.targetPort }}
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: my-database-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-database-secret
                  key: password
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: my-database-secret
                  key: url
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth-secret 
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret 
                  key: CLIENT_SECRET
            - name: AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth-secret 
                  key: AUTH_DOMAIN
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-secret 
                  key: API_TOKEN
      imagePullSecrets:
        - name: my-registry-secret

