apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ui-ingress
  namespace: web-ui
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  rules:
  - host: pinfo3.unige.ch
    http:
      paths:
      - path: "/(.*)(/|$)"
        pathType: Prefix
        backend:
          service:
            name: web-ui-service
            port:
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-management-ingress
  namespace: stock-management
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1/$3"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 5m
    nginx.ingress.kubernetes.io/proxy-body-size: 15m
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.org/client-max-body-size: 15m
spec:
  tls:
  - hosts:
    - pinfo3.unige.ch
    secretName: letsencrypt-prod
  rules:
  - host: pinfo3.unige.ch
    http:
      paths:
      - path: "/api/(stock)(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: stock-management-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-ingress
  namespace: payment
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1/$3"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 5m
    nginx.ingress.kubernetes.io/proxy-body-size: 15m
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.org/client-max-body-size: 15m
spec:
  tls:
  - hosts:
    - pinfo3.unige.ch
    secretName: letsencrypt-prod
  rules:
  - host: pinfo3.unige.ch
    http:
      paths:
      - path: "/api/(payment)(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: payment-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customization-ingress
  namespace: customization
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1/$3"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 5m
    nginx.ingress.kubernetes.io/proxy-body-size: 15m
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.org/client-max-body-size: 15m
spec:
  tls:
  - hosts:
    - pinfo3.unige.ch
    secretName: letsencrypt-prod
  rules:
  - host: pinfo3.unige.ch
    http:
      paths:
      - path: "/api/(customization)(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: customization-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.backoffice.name }}-ingress
  namespace: {{ .Values.backoffice.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1/$3"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 5m
    nginx.ingress.kubernetes.io/proxy-body-size: 15m
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.org/client-max-body-size: 15m
spec:
  tls:
  - hosts:
    - pinfo3.unige.ch
    secretName: letsencrypt-prod
  rules:
  - host: pinfo3.unige.ch
    http:
      paths:
      - path: "/api/(stats)(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.backoffice.name }}-service
            port:
              number: {{ .Values.backoffice.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stats-jwt-ingress
  namespace: stats-jwt
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1/$3"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 5m
    nginx.ingress.kubernetes.io/proxy-body-size: 15m
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.org/client-max-body-size: 15m
spec:
  tls:
  - hosts:
    - pinfo3.unige.ch
    secretName: letsencrypt-prod
  rules:
  - host: pinfo3.unige.ch
    http:
      paths:
      - path: "/api/(jwt)(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: stats-jwt-service
            port:
              number: 80
