apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webui.name }}-service
  namespace: {{ .Values.webui.namespace}}
spec:
  selector:
    app: {{ .Values.webui.name }}
  ports:
  - name: http
    port: {{ .Values.webui.port }}
    targetPort: {{ .Values.webui.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.customization.name }}-service
  namespace: {{ .Values.customization.namespace}}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.customization.port }}
    targetPort: {{ .Values.customization.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.payment.name }}-service
  namespace: {{ .Values.payment.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.payment.port }}
    targetPort: {{ .Values.payment.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stockmanagement.name }}-service
  namespace: {{ .Values.stockmanagement.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.stockmanagement.port }}
      targetPort: {{ .Values.stockmanagement.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.stockmanagement.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backoffice.name }}-service
  namespace: {{ .Values.backoffice.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backoffice.port }}
      targetPort: {{ .Values.backoffice.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.backoffice.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.statsjwt.name }}-service
  namespace: {{ .Values.statsjwt.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.statsjwt.port }}
      targetPort: {{ .Values.statsjwt.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.statsjwt.name }}
