apiVersion: v1
kind: Service
metadata:
  name: web-ui-service
  namespace: web-ui
spec:
  selector:
    app: web-ui
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: customization-service
  namespace: customization
spec:
  selector:
    app: customization
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment
spec:
  selector:
    app: payment
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: stock-management-service
  namespace: stock-management
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: stock-management
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backoffice.name }}-service
  namespace: {{ .Values.backoffice.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backoffice.port }}
      targetPort: {{ .Values.backoffice.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.backoffice.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: stats-jwt-service
  namespace: stats-jwt
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: stats-jwt
