apiVersion: v1
kind: Service
metadata:
  name: web-ui-service
  namespace: web-ui
spec:
  selector:
    app: web-ui
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stock-management-service
  namespace: stock-management
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: stock-management
---
apiVersion: v1
kind: Service
metadata:
  name: back-office-service
  namespace: back-office
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: back-office
---
apiVersion: v1
kind: Service
metadata:
  name: back-office-service
  namespace: back-office
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: back-office
