apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webui.name }}-service
  namespace: {{ .Values.webui.namespace}}
spec:
  selector:
    app: {{ .Values.webui.name }}
  ports:
  - name: http
    port: {{ .Values.webui.port }}
    targetPort: {{ .Values.webui.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.customization.name }}-service
  namespace: {{ .Values.customization.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.customization.port }}
      targetPort: {{ .Values.customization.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.customization.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.payment.name }}-service
  namespace: {{ .Values.payment.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.payment.port }}
      targetPort: {{ .Values.payment.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.payment.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stockmanagement.name }}-service
  namespace: {{ .Values.stockmanagement.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.stockmanagement.port }}
      targetPort: {{ .Values.stockmanagement.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.stockmanagement.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.name }}-service
  namespace: {{ .Values.auth.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.auth.port }}
      targetPort: {{ .Values.auth.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.auth.name }}

  
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.statistics.name }}-service
  namespace: {{ .Values.statistics.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.statistics.port }}
      targetPort: {{ .Values.statistics.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.statistics.name }}

