apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-management-deployment
  namespace: stock-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-management-deployment
  template:
    metadata:
      labels:
        app: stock-management-deployment
    spec:
      containers:
        - name: stock-management-deployment
          image: registry.gitlab.unige.ch/pinfo-2023/pinfo-2/project-ecommerce/stock-management:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: my-database-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-database-secret
                  key: password
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: my-database-secret
                  key: url
      imagePullSecrets:
        - name: my-registry-secret
