apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stockmanagement.name }}-deployment
  namespace: {{ .Values.stockmanagement.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.stockmanagement.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.stockmanagement.name }}
    spec:
      containers:
        - name: {{ .Values.stockmanagement.name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.group }}/{{ .Values.stockmanagement.imagename }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          ports:
            - containerPort: {{ .Values.stockmanagement.targetPort }}
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: my-database-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-database-secret
                  key: password
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: my-database-secret
                  key: url
      imagePullSecrets:
        - name: my-registry-secret
