apiVersion: v1
kind: Service
metadata:
  name: stock-management-service
  namespace: stock-management
spec:
  selector:
    app: stock-management-deployment
  ports:
  - name: http
    port: 8080
    targetPort: 8080

