apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-deployment
  namespace: web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
        - name: web-ui
          image: registry.gitlab.unige.ch/pinfo-2023/pinfo-2/project-ecommerce/web-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: my-database-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-database-secret
                  key: password
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: my-database-secret
                  key: url
      imagePullSecrets:
        - name: my-registry-secret
